const fs = require('fs');

let content = fs.readFileSync('app/api/patches/route.ts', 'utf8');

content = content.replace(
  /const \{ project_id, repository_id, file_path, original_content, updated_content \} = await req\.json\(\);/,
  `const { project_id, repository_id, file_path, original_content, updated_content, model } = await req.json();`
);

content = content.replace(
  /unified_diff: "AI Generated Diff",\s*status: 'pending'/,
  `unified_diff: "AI Generated Diff",
         status: 'pending',
         explanation: model ? \`Generated by \${model}\` : "AI Generated Patch"`
);

fs.writeFileSync('app/api/patches/route.ts', content);
