const fs = require('fs');

let content = fs.readFileSync('app/(dashboard)/projects/[id]/page.tsx', 'utf8');

const regex = /const handleCreatePullRequest = async \(\) => \{[\s\S]*?addNotification\("Pull Request Failed", err\.message, "error"\);\s*\}\s*\}/;

const newPrCode = `const handleCreatePullRequest = async () => {
    try {
      const res = await fetch('/api/github/pull-request', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          project_id: project?.id,
          branch_name: \`trace-one/fix-\${Date.now()}\`,
          title: 'Fix issue identified by Trace One AI',
          description: 'This PR fixes an issue automatically generated by Trace One AI.\\n\\nModified files:\\n- ' + (diffState?.filePath || selectedFile),
          files: [
            {
              path: diffState?.filePath || selectedFile || 'src/controllers/analytics.ts',
              content: diffState?.modified || filesMap[selectedFile] || ''
            }
          ],
          investigation_id: (diffState as any)?.investigation_id
        })
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Failed to create PR');
      setPrCreated(true);
      addNotification("Pull Request Created", \`Opened PR: \${data.url}\`, "success");
      addChatMessage(projectId, "assistant", \`Fix pushed to GitHub.\\n[View Pull Request](\${data.url})\`);
    } catch (err: any) {
      addNotification("Pull Request Failed", err.message, "error");
    }
  }`;

content = content.replace(regex, newPrCode);
fs.writeFileSync('app/(dashboard)/projects/[id]/page.tsx', content);
