import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { generateUnifiedDiff } from "@/lib/utils/diff";

export async function POST(req: NextRequest) {
  try {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();
    
    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { 
      project_id, 
      repository_id, 
      file_path, 
      original_content, 
      updated_content, 
      model,
      root_cause,
      confidence_score,
      risk_analysis,
      time_estimate_minutes
    } = await req.json();

    if (!project_id || !repository_id) {
       return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
    }

    // 1. Check if there's an incident for this project
    let { data: incident } = await supabase
      .from('incidents')
      .select('id')
      .eq('project_id', project_id)
      .order('created_at', { ascending: false })
      .limit(1)
      .maybeSingle();

    if (!incident) {
      const { data: newIncident, error: incErr } = await supabase
        .from('incidents')
        .insert({
           project_id,
           title: 'AI Investigation',
           error_type: 'Manual Trigger',
           status: 'open',
           severity: 'medium'
        })
        .select('id')
        .single();
      
      if (incErr) throw incErr;
      incident = newIncident;
    }

    // 2. Check if there's an investigation
    let { data: investigation } = await supabase
      .from('investigations')
      .select('id')
      .eq('incident_id', incident.id)
      .order('created_at', { ascending: false })
      .limit(1)
      .maybeSingle();

    if (!investigation) {
      const { data: newInv, error: invErr } = await supabase
        .from('investigations')
        .insert({
           incident_id: incident.id,
           status: 'completed',
           root_cause: root_cause || null,
           confidence_score: confidence_score || null,
           risk_analysis: risk_analysis || null,
           time_estimate_minutes: time_estimate_minutes || null
        })
        .select('id')
        .single();
        
      if (invErr) throw invErr;
      investigation = newInv;
    } else {
      // Update existing investigation with diagnostics if provided
      const updateData: any = {};
      if (root_cause) updateData.root_cause = root_cause;
      if (confidence_score) updateData.confidence_score = confidence_score;
      if (risk_analysis) updateData.risk_analysis = risk_analysis;
      if (time_estimate_minutes) updateData.time_estimate_minutes = time_estimate_minutes;
      updateData.status = 'completed';

      if (Object.keys(updateData).length > 0) {
        await supabase
          .from('investigations')
          .update(updateData)
          .eq('id', investigation.id);
      }
    }

    // Create a record in analysis_runs
    await supabase.from('analysis_runs').insert({
      investigation_id: investigation.id,
      step_name: 'AI Analysis',
      output: root_cause || `AI Analysis of ${file_path}`,
      status: 'success',
      completed_at: new Date().toISOString()
    });

    const actualDiff = generateUnifiedDiff(file_path, original_content, updated_content);

    // 3. Create the patch
    const { data: patch, error: patchErr } = await supabase
      .from('patches')
      .insert({
         investigation_id: investigation.id,
         repository_id,
         file_path,
         original_content,
         updated_content,
         unified_diff: actualDiff,
         status: 'pending',
         explanation: model ? `Generated by ${model}` : "AI Generated Patch"
      })
      .select('id')
      .single();

    if (patchErr) throw patchErr;

    return NextResponse.json({ success: true, patch_id: patch.id, investigation_id: investigation.id });

  } catch (error: any) {
    console.error("Patch store error:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
