import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { generateUnifiedDiff } from "@/lib/utils/diff";

export async function POST(req: NextRequest) {
  try {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();
    
    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { project_id, repository_id, file_path, original_content, updated_content, model } = await req.json();

    if (!project_id || !repository_id) {
       return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
    }

    // 1. Check if there's an incident for this project
    let { data: incident } = await supabase
      .from('incidents')
      .select('id')
      .eq('project_id', project_id)
      .order('created_at', { ascending: false })
      .limit(1)
      .maybeSingle();

    if (!incident) {
      const { data: newIncident, error: incErr } = await supabase
        .from('incidents')
        .insert({
           project_id,
           title: 'AI Investigation',
           error_type: 'Manual Trigger',
           status: 'open',
           severity: 'medium'
        })
        .select('id')
        .single();
      
      if (incErr) throw incErr;
      incident = newIncident;
    }

    // 2. Check if there's an investigation
    let { data: investigation } = await supabase
      .from('investigations')
      .select('id')
      .eq('incident_id', incident.id)
      .order('created_at', { ascending: false })
      .limit(1)
      .maybeSingle();

    if (!investigation) {
      const { data: newInv, error: invErr } = await supabase
        .from('investigations')
        .insert({
           incident_id: incident.id,
           status: 'completed'
        })
        .select('id')
        .single();
        
      if (invErr) throw invErr;
      investigation = newInv;
    }

    const actualDiff = generateUnifiedDiff(file_path, original_content, updated_content);

    // 3. Create the patch
    const { data: patch, error: patchErr } = await supabase
      .from('patches')
      .insert({
         investigation_id: investigation.id,
         repository_id,
         file_path,
         original_content,
         updated_content,
         unified_diff: actualDiff,
         status: 'pending',
         explanation: model ? `Generated by ${model}` : "AI Generated Patch"
      })
      .select('id')
      .single();

    if (patchErr) throw patchErr;

    return NextResponse.json({ success: true, patch_id: patch.id, investigation_id: investigation.id });

  } catch (error: any) {
    console.error("Patch store error:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
